name: SchwitzerWars
main: Fludixx\SchwitzerWars\Main
version: 0.1
api: [3.0.0-ALPHA12, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5]
author: Fludixx
commands:
    pw:
      description: "/pw [WORLD]"
    pwsign:
      description: "/pwsign [ARENA]"
permissions:
  pw.start:
    description: "Allows you to ue /pw start"
    default: op